OKProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('invoice_manager.urls')),
]

invoice_manager/urls.py
from django.urls import path
from .views import *


app_name = "invoice_manager"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("items", ItemsView.as_view(), name="items"),
    path("customers", CustomersView.as_view(), name="customers"),
    path("customers/<int:pk>/details", CustomerDetailView.as_view(), name="customer_detail"),
    path("invoices", InvoiceListView.as_view(), name="invoices"),
    path("invoices/creation", CreateInvoiceView.as_view(), name="invoice_creation"),
    path("invoices/<int:pk>/details", InvoiceDetailView.as_view(), name="invoice_detail"),
]

ajax_urlpatterns = [
    path("login", login_user, name="login_user"),

    path("items/<int:pk>/delete", item_delete, name="item_delete"),
    path("items/<int:pk>/update", item_update, name="item_update"),
    path("items/create", item_create, name="item_create"),

    path("customers/create", customer_create, name="customer_create"),
    path("customers/<int:pk>/update", customer_update, name="customer_update"),

    path("invoices/create", invoice_create, name="invoice_create"),
]

urlpatterns += ajax_urlpatterns

invoice_manager/models.py
from django.db import models
from django.contrib.auth.models import User
import json


# Create your models here.


class Customer(models.Model):
    name = models.CharField(max_length=255, unique=True)
    phone_number = models.CharField(max_length=15, unique=True)
    address = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def get_pending_amount(self):
        amount = 0
        for invoice in self.invoices.all():
            amount += invoice.get_pending_amount()
        return amount

    def __str__(self):
        return self.name


class Invoice(models.Model):
    title = models.CharField(max_length=255, blank=True, null=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name="invoices")
    amount_paid = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    items = models.JSONField(default=list) # [{name, rate, quantity}, ...]

    def get_invoice_title(self):
        if self.title:
            return self.title
        return self.customer.name + '\'s invoice No. ' + str(self.pk)

    def get_total_amount(self):
        amount = 0
        for item in self.items:
            amount += int(item["rate"]) * int(item["quantity"])
        return amount

    def get_total_items(self):
        return len(self.items)

    def get_pending_amount(self):
        return self.get_total_amount() - self.amount_paid

    def add_payment(self, amount):
        if amount > self.get_pending_amount():
            amount -= self.get_pending_amount()
        self.amount_paid += amount
        self.save()

    def make_item_list(self, names, rates, quantities):
        items = []
        for i in range(len(names)):
            items.append({"name": names[i], "rate": rates[i], "quantity": quantities[i]})
        self.items = (items)


    def __str__(self):
        return self.title or self.customer.name + '\'s invoice with amount ' + str(self.amount_paid) + '/' + str(self.get_total_amount())


class Item(models.Model):
    name = models.CharField(max_length=255, unique=True)
    rate = models.IntegerField()

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15, unique=True)
    is_employee = models.BooleanField(default=True)

    def __str__(self):
        return self.user.username

invoice_manager/forms.py
from django import forms

from .models import Item, Customer


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ("name", "rate")
        labels = {
            "name": "Item Name",
            "rate": "Rate",
        }


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ("name", "phone_number")
        labels = {
            "name": "Customer Name",
            "phone_number": "Phone Number",
        }

invoice_manager/views.py
from datetime import timedelta
from lib2to3.fixes.fix_input import context

from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.db.models import Sum
from django.http import JsonResponse
from django.utils import timezone
from django.views.generic import TemplateView, CreateView, DeleteView, UpdateView, ListView, DetailView
from .models import Invoice, Customer, Item

import json


def login_user(request):
    username = request.POST.get("username")
    password = request.POST.get("password")
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        return JsonResponse({"success": True})
    else:
        return JsonResponse({"success": False})


# region Item Methods
@login_required
def item_create(request):
    if request.method == "POST":
        if not (request.user.profile.is_employee and request.user.is_superuser):
            return JsonResponse({"success": False, "reason": "Only employees and admins can create items"})
        name = request.POST.get("name")
        rate = request.POST.get("rate")
        try:
            item = Item()
            item.name = name
            item.rate = rate
            item.save()
            return JsonResponse({"success": True, "item": {"pk": item.pk, "name": item.name, "rate": item.rate},
                                 "reason": "Item created successfully"})
        except IntegrityError as e:
            return JsonResponse({"success": False, "reason": f"Item with name \"{name}\" already exists"})

    return JsonResponse({"success": False, "reason": "Invalid request"})


@login_required
def item_delete(request, pk):
    print(pk)
    if request.method == "POST":
        if not (request.user.profile.is_employee and request.user.is_superuser):
            return JsonResponse({"success": False, "reason": "Only employees and admins can delete items"})
        try:
            item = Item.objects.get(pk=pk)
            item.delete()
            return JsonResponse({"success": True, "reason": "Item deleted successfully"})
        except Exception as e:
            print(e)
            return JsonResponse({"success": False, "reason": "Item not found"})

    return JsonResponse({"success": False, "reason": "Invalid request"})


@login_required
def item_update(request, pk):
    if request.method == "POST":
        if not (request.user.profile.is_employee and request.user.is_superuser):
            return JsonResponse({"success": False, "reason": "Only employees and admins can update items"})
        name = request.POST.get("name")
        rate = request.POST.get("rate")
        item = Item.objects.get(pk=pk)
        item.name = name
        item.rate = rate
        item.save()
        return JsonResponse(
            {"success": True, "item": {"name": item.name, "rate": item.rate}, "reason": "Item updated successfully"})

    return JsonResponse({"success": False, "reason": "Invalid request"})


# endregion

# region Customer Methods

@login_required
def customer_create(request):
    if request.method == "POST":
        if not (request.user.profile.is_employee and request.user.is_superuser):
            return JsonResponse({"success": False, "reason": "Only employees and admins can create customers"})
        name = request.POST.get("name")
        phone_number = request.POST.get("phone_number")
        address = request.POST.get("address")
        try:
            customer = Customer()
            customer.name = name
            customer.phone_number = phone_number
            customer.address = address
            customer.save()
            return JsonResponse({"success": True, "customer": {"pk": customer.pk, "name": customer.name,
                                                               "phone_number": customer.phone_number,
                                                               "address": customer.address,
                                                               "pending_amount": customer.get_pending_amount()},
                                 "reason": "Customer created successfully"})
        except IntegrityError as e:
            return JsonResponse({"success": False, "reason": f"Customer with name \"{name}\" already exists"})

    return JsonResponse({"success": False, "reason": "Invalid request"})


@login_required
def customer_update(request, pk):
    if request.method == "POST":
        if not (request.user.profile.is_employee and request.user.is_superuser):
            return JsonResponse({"success": False, "reason": "Only employees and admins can update customers"})
        name = request.POST.get("name")
        phone_number = request.POST.get("phone_number")
        address = request.POST.get("address")
        customer = Customer.objects.get(pk=pk)
        customer.name = name
        customer.phone_number = ''.join(c for c in phone_number if c.isdigit())
        customer.address = address
        customer.save()
        return JsonResponse({"success": True, "customer": {"name": customer.name, "phone_number": customer.phone_number,
                                                           "address": customer.address,
                                                           "pending_amount": customer.get_pending_amount()},
                             "reason": "Customer updated successfully"})

    return JsonResponse({"success": False, "reason": "Invalid request"})


# endregion

# region Invoice Methods
@login_required
def invoice_create(request):
    if request.method == "POST":

        if not (request.user.profile.is_employee and request.user.is_superuser):
            return JsonResponse({"success": False, "reason": "Only employees and admins can create invoices"})

        data = json.loads(request.body)

        title = data["title"]
        customer_pk = data["customer"]
        items = data["items"]
        names = items["name"]
        rates = items["rate"]
        quantities = items["quantity"]

        try:
            customer = Customer.objects.get(pk=customer_pk)
        except Exception as e:
            return JsonResponse({"success": False, "reason": f"Customer with pk \"{customer_pk}\" not found"})

        try:
            invoice = Invoice()
            invoice.customer = customer
            invoice.created_by = request.user
            invoice.make_item_list(names, rates, quantities)
            invoice.save()
            invoice.title = title or f"{customer}'s Invoice No. {invoice.id}"
            invoice.save()
            return JsonResponse({"success": True, "invoice": {"pk": invoice.pk, "title": invoice.get_invoice_title(),
                                                              "amount_paid": invoice.amount_paid,
                                                              "total_amount": invoice.get_total_amount(),
                                                              "pending_amount": invoice.get_pending_amount(),
                                                              "items": invoice.items},
                                 "reason": "Invoice created successfully"})
        except Exception as e:
            return JsonResponse({"success": False, "reason": f"{e}"})

    return JsonResponse({"success": False, "reason": "Invalid request"})

# endregion


class IndexView(TemplateView):
    template_name = "invoice_manager/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["invoices"] = Invoice.objects.filter(created_at__gte=timezone.now() - timedelta(days=1)).order_by("-id")
        context["customers"] = Customer.objects.filter(created_at__gte=timezone.now() - timedelta(days=1)).order_by(
            "-id")
        return context


class ItemsView(ListView):
    template_name = "invoice_manager/item_list.html"
    model = Item
    context_object_name = "items"


class CustomersView(ListView):
    template_name = "invoice_manager/customer_list.html"
    model = Customer
    context_object_name = "customers"


    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        customers = Customer.objects.all()
        pending_amounts = [customer.get_pending_amount() for customer in customers]
        combined_list = zip(customers, pending_amounts)
        combined_list = sorted(combined_list, key=lambda x: x[1], reverse=True)
        sorted_customers, sort_amounts = zip(*combined_list)

        print(sorted_customers)
        context["customers"] = sorted_customers

        return context



class CustomerDetailView(DetailView):
    template_name = "invoice_manager/customer_detail.html"
    model = Customer
    context_object_name = "customer"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        invoices = Invoice.objects.filter(customer=self.object)
        context["invoices"] = Invoice.objects.filter(customer=self.object).order_by("-id")
        return context


class InvoiceListView(ListView):
    template_name = "invoice_manager/invoice_list.html"
    model = Invoice
    context_object_name = "invoices"
    ordering = "-id"


class CreateInvoiceView(TemplateView):
    template_name = "invoice_manager/invoice_create.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["customers"] = Customer.objects.all()
        context["items"] = Item.objects.all()
        return context


class InvoiceDetailView(DetailView):
    template_name = "invoice_manager/invoice_detail.html"
    model = Invoice
    context_object_name = "invoice"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        items = self.object.items
        for item in items:
            item["total"] = int(item["rate"]) * int(item["quantity"])

templates/invoice_manager/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Invoice Manager{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/1a5c093d10.js" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-sm">
        <a class="navbar-brand" href="{% url 'invoice_manager:index' %}">OkPrints</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'invoice_manager:items' %}">Items</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'invoice_manager:customers' %}">Customers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'invoice_manager:invoices' %}">Invoices</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

templates/invoice_manager/customer_detail.html
{% extends 'invoice_manager/base.html' %}

{% load widget_tweaks %}

{% block title %}{{ customer.name }} Details{% endblock %}

{% block content %}
    <h1>{{ customer.name }} Details</h1>
    <p>Phone Number: {{ customer.phone_number }}</p>
    <p>Address: {{ customer.address }}</p>
    <p>Pending Amount: {{ customer.get_pending_amount }}</p>

    <h2>Invoices</h2>
    <ul>
        <table id="invoice-table" class="table table-striped">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Created at</th>
                    <th>Created By</th>
                    <th>Items</th>
                    <th>Total Amount</th>
                    <th>Paid Amount</th>
                    <th>Pending Amount</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for invoice in invoices %}
                    <tr>
                        <td>{{ invoice.title }}</td>
                        <td>{{ invoice.created_at }}</td>
                        <td>{{ invoice.created_by }}</td>
                        <td>{{ invoice.get_total_items }}</td>
                        <td>{{ invoice.get_total_amount }}</td>
                        <td>{{ invoice.amount_paid }}</td>
                        <td>{{ invoice.get_pending_amount }}</td>
                        <td>
                            <a class="btn btn-primary" href="{% url 'invoice_manager:invoice_detail' invoice.id %}"><i class="fas fa-arrow-up-right-from-square"></i></a>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </ul>
{% endblock %}

templates/invoice_manager/customer_list.html
{% extends 'invoice_manager/base.html' %}

{% load widget_tweaks %}

{% block title %}Customers{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="text-center">Customers</h1>
    <button type="button" class="btn red-button mt-3 mb-3" data-toggle="modal" data-target="#create-modal">Create New Customer</button>
    <div class="row justify-content-center">
      <table id="customer-table" class="table table-striped">
        <thead>
          <tr>
            <th>Customer <input onkeyup="FilterList()" type="text" class="form-control" id="search-input" placeholder="Search..."></th>
            <th>Phone Number</th>
            <th>Address</th>
            <th>Pending Amount</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for customer in customers %}
            <tr data-customer-id="{{ customer.pk }}">
                <td>{{ customer.name }}</td>
                <td>{{ customer.phone_number }}</td>
                <td>{{ customer.address }}</td>
                <td>{{ customer.get_pending_amount }}</td>
                <td>
                <button class="btn btn-primary" onclick="onCustomerUpdateButtonClick({{ customer.pk }})"><i class="fas fa-edit"></i></button>
                <a href="{% url 'invoice_manager:customer_detail' pk=customer.pk %}"><button class="btn btn-primary">View</button></a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

    {% include 'invoice_manager/partials/customer-modals.html' %}

    <script>

    function onCustomerUpdateButtonClick(customerId) {
        var item = $('tr[data-customer-id="' + customerId + '"]');
        var modal = $('#update-modal');
        var name = item.find('td:nth-child(1)').text();
        var phone_number = item.find('td:nth-child(2)').text();
        var address = item.find('td:nth-child(3)').text();
        modal.find('#update-name').val(name);
        modal.find('#update-phone_number').val(phone_number);
        modal.find('#update-address').val(address);
        modal.find('#loader-update-modal').hide();
        modal.find('#update-modal-error-message').hide();
        modal.find('#update-modal-title').text(`Update ${name}`);
        modal.find('#update-modal-confirm-message').text(`Are you sure you want to update ${name}?`);
        modal.find('#confirm-update-customer').data('customer-id', customerId);
        modal.modal('show');
    }

    function onCustomerModalUpdateButtonClick(){
        var customerId = $('#confirm-update-customer').data('customer-id');

        var customer = $('tr[data-customer-id="' + customerId + '"]');
        var name = $('#update-name').val();
        var phone_number = $('#update-phone_number').val();
        var address = $('#update-address').val();
        var modal = '#update-modal';
        var loaderId = '#loader-update-modal';
        var errorMessageId = '#update-modal-error-message';

        if (name === '' || phone_number === '') {
          $(loaderId).hide();
          $(errorMessageId).html('Name and phone number are required').show();
          return;
        }
        $.ajax({
          type: 'POST',
          url: `customers/${customerId}/update`,
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
              },
          data: {
            'name': name,
            'phone_number': phone_number,
            'address': address
          },
          beforeSend: function() {
            $(loaderId).show();
            $(errorMessageId).hide();
          },
          success: function(response) {
            if (response.success) {
              $(modal).modal('hide');
              $(loaderId).hide();
              $(errorMessageId).hide();
              // Update table to reflect updated item
              customer.find('td:nth-child(1)').text(response.customer.name);
              customer.find('td:nth-child(2)').text(response.customer.phone_number);
              customer.find('td:nth-child(3)').text(response.customer.address);
            } else {
              $(loaderId).hide();
              if (response.reason) {
                $(errorMessageId).html(response.reason).show();
              } else {
                $(errorMessageId).html(response.error).show();
              }
            }
          },
          error: function(xhr, status, error) {
            $(loaderId).hide();
            $(errorMessageId).html('Error: ' + error).show();
          }
        });
    }

    function onCustomerCreateButtonClick() {
        $('#create-modal-title').text('Create Customer');
        const modal = $('#create-modal');
        const loaderId = '#loader-create-modal';
        const errorMessageId = '#create-modal-error-message';
        const name = $('#create-name').val();
        const phone_number = $('#create-phone_number').val();
        const address = $('#create-address').val();

        if (name === '' || phone_number === '') {
          $(loaderId).hide();
          $(errorMessageId).html('Name and phone number are required').show();
          return;
        }
        $.ajax({
          type: 'POST',
          url: '{% url 'invoice_manager:customer_create' %}',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
              },
          data: {
            'name': name,
            'phone_number': phone_number,
            'address': address
          },
          beforeSend: function() {
            $(loaderId).show();
            $(errorMessageId).hide();
          },
          success: function(response) {
            if (response.success) {
                modal.modal('hide');
                $(loaderId).hide();
                $(errorMessageId).hide();
                // Update table to reflect updated item
                var newRow = $('<tr>');
                newRow.attr('data-customer-id', response.customer.pk);
                newRow.append('<td>' + response.customer.name + '</td>');
                newRow.append('<td>' + response.customer.phone_number + '</td>');
                newRow.append('<td>' + response.customer.address + '</td>');
                newRow.append('<td>' + response.customer.pending_amount + '</td>');
                newRow.append('<td><button class="btn btn-primary" onclick="onCustomerUpdateButtonClick(' + response.customer.pk + ')"><i class="fas fa-edit"></i></button></td>');
                newRow.append(`<td><a href="customers/${response.customer.pk}/details"><button class="btn btn-primary">View</button></a></td>`);
              $('#customer-table tbody').append(newRow);
            } else {
              $(loaderId).hide();
              if (response.reason) {
                $(errorMessageId).html(response.reason).show();
              } else {
                $(errorMessageId).html(response.error).show();
              }
            }
          },
          error: function(xhr, status, error) {
            $(loaderId).hide();
            $(errorMessageId).html('Error: ' + error).show();
          }
        });
    }
                        

    $('#update-customer-form').on('submit', function(e) {
        e.preventDefault();
    });
    $('#create-customer-form').on('submit', function(e) {
        e.preventDefault();
    });
    </script>

{% endblock %}

templates/invoice_manager/index.html
{% extends 'invoice_manager/base.html' %}

{% block title %}OkPrints Manager{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <h1>Welcome {{ user.username }}!</h1>
    <div class="row">
      <div class="col">
        <h2>Recent Invoices</h2>
        <ul>
          {% for invoice in invoices %}
            <li>
              <a class="index-invoice" href="{% url 'invoice_manager:invoice_detail' invoice.id %}">
                {{ invoice.created_by }} created an invoice for {{ invoice.customer.name }} of RS {{ invoice.get_total_amount }}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
      <div class="col">
        <h2>New Customers</h2>
        <ul>
          {% for customer in customers %}
            <li>
              <a class="index-invoice" href="{% url "invoice_manager:customer_detail" pk=customer.pk%}">
                {{ customer.name }}
              </a>
            </li>
          {% endfor %}
        </ul>
      </div>
    </div>
  {% else %}

    <h1>Welcome to OkPrints Invoice Manager!</h1>
      <form style="width: 50%; left: 25%; position: relative" class="index-login-form mt-5 mb-5" method="post" action="{% url 'invoice_manager:login_user' %}">
        {% csrf_token %}
        <div class="form-group">
          <label for="username">Username</label>
          <input type="text" class="form-control" id="username" name="username" autocomplete="off">
        </div>
        <div class="form-group">
          <label for="password">Password</label>
          <input type="password" class="form-control" id="password" name="password" autocomplete="off">
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
      </form>
  {% endif %}

    <script>
    $('.index-login-form').on('submit', function(e) {
      e.preventDefault();
      var url = $(this).attr('action');
      var data = $(this).serialize();
      $.post(url, data, function(response) {
        if (response.success) {
          window.location.href = '{% url "invoice_manager:index" %}';
        } else {
          console.log('Login failed');
        }
      });
    });
    </script>
{% endblock %}

templates/invoice_manager/invoice_detail.html
{% extends "invoice_manager/base.html" %}

{% block title %}Invoice{% endblock %}

{% block content %}
    <h1>Invoice</h1>
    <a href="{% url 'invoice_manager:invoices' %}" class="btn red-button mt-3 mb-3"><i class="fas fa-arrow-left"></i> Back to Invoices</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Rate</th>
                <th>Quantity</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
                <tr>
                    <td>{{ item.name }}</td>
                    <td>{{ item.rate }}</td>
                    <td>{{ item.quantity }}</td>
                    <td>{{ item.total }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/invoice_manager/invoice_list.html
{% extends 'invoice_manager/base.html' %}

{% block title %}Invoices{% endblock %}

{% block content %}
    <h1>Invoices</h1>
    <a href="{% url 'invoice_manager:invoice_creation' %}" class="btn red-button mt-3 mb-3">Create New Invoice</a>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Created At</th>
                <th>Created By</th>
                <th>Number of Items</th>
                <th>Total Amount</th>
                <th>Paid Amount</th>
                <th>Pending Amount</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for invoice in invoices %}
                <tr>
                    <td>{{ invoice.title }}</td>
                    <td>{{ invoice.created_at }}</td>
                    <td>{{ invoice.created_by }}</td>
                    <td>{{ invoice.get_total_items }}</td>
                    <td>{{ invoice.get_total_amount }}</td>
                    <td>{{ invoice.amount_paid }}</td>
                    <td>{{ invoice.get_pending_amount }}</td>
                    <td>
                        <a class="btn btn-primary" href="{% url 'invoice_manager:invoice_detail' pk=invoice.pk %}" title="Details"><i class="fas fa-arrow-up-right-from-square"></i></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}